### ISSUE TITLE
npm Err!

### ISSUE THREAD

**Issue by LukasSchondorff** [DomainDrivenArchitecture/dda-managed-ide#34]
10:42:16.042 [operate-15] ERROR pallet.execute - localhost #> install-apm-plugin-ink (atom.clj:49) : FAIL
10:42:16.043 [operate-15] WARN  pallet.local.execute - localhost 
10:42:16.043 [operate-15] WARN  pallet.local.execute - localhost npm ERR! addLocal Could not install /tmp/d-11836-12704-153uqs4.7tzjdzpvi/package.tgz
10:42:16.043 [operate-15] WARN  pallet.local.execute - localhost npm ERR! Linux 4.13.0-38-generic
10:42:16.043 [operate-15] WARN  pallet.local.execute - localhost npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/test-user/.atom/.apm/.apmrc" "--userconfig" "/home/test-user/.atom/.apmrc" "install" "/tmp/d-11836-12704-153uqs4.7tzjdzpvi/package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
10:42:16.043 [operate-15] WARN  pallet.local.execute - localhost npm ERR! node v6.9.5
10:42:16.043 [operate-15] WARN  pallet.local.execute - localhost npm ERR! npm  v3.10.10
10:42:16.043 [operate-15] WARN  pallet.local.execute - localhost npm ERR! path /home/test-user/.atom/.apm/ink/0.8.3
10:42:16.043 [operate-15] WARN  pallet.local.execute - localhost npm ERR! code EACCES
10:42:16.043 [operate-15] WARN  pallet.local.execute - localhost npm ERR! errno -13
10:42:16.044 [operate-15] WARN  pallet.local.execute - localhost npm ERR! syscall mkdir
10:42:16.044 [operate-15] WARN  pallet.local.execute - localhost 
10:42:16.044 [operate-15] WARN  pallet.local.execute - localhost npm ERR! Error: EACCES: permission denied, mkdir '/home/test-user/.atom/.apm/ink/0.8.3'
10:42:16.044 [operate-15] WARN  pallet.local.execute - localhost npm ERR!     at Error (native)
10:42:16.044 [operate-15] WARN  pallet.local.execute - localhost npm ERR!  { Error: EACCES: permission denied, mkdir '/home/test-user/.atom/.apm/ink/0.8.3'
10:42:16.044 [operate-15] WARN  pallet.local.execute - localhost npm ERR!     at Error (native)
10:42:16.045 [operate-15] WARN  pallet.local.execute - localhost npm ERR!   errno: -13,
10:42:16.045 [operate-15] WARN  pallet.local.execute - localhost npm ERR!   code: 'EACCES',
10:42:16.046 [operate-15] WARN  pallet.local.execute - localhost npm ERR!   syscall: 'mkdir',
10:42:16.047 [operate-15] WARN  pallet.local.execute - localhost npm ERR!   path: '/home/test-user/.atom/.apm/ink/0.8.3' }
10:42:16.047 [operate-15] WARN  pallet.local.execute - localhost npm ERR! 
10:42:16.047 [operate-15] WARN  pallet.local.execute - localhost npm ERR! Please try running this command again as root/Administrator.
10:42:16.047 [operate-15] WARN  pallet.local.execute - localhost 
10:42:16.047 [operate-15] WARN  pallet.local.execute - localhost npm ERR! Please include the following file with any support request:
10:42:16.047 [operate-15] WARN  pallet.local.execute - localhost npm ERR!     /tmp/apm-install-dir-11836-12704-1owo204.t0mokcsor/npm-debug.log
10:42:16.048 [operate-15] WARN  pallet.local.execute - localhost

**Comment by jerger** [comment]
fixed
